In [2]:
import numpy as np

In [3]:
# 0 dimensional array or a scalar
my0dArray = np.array(42)

# # 1 dimensional array (its a list)
my1dArray = np.array([1,2,3])

# 2 dimensional array (its a list of lists)
my2dArray = np.array([[1,2,3],[4,5,6]])

In [4]:
# Creating numpy arrays that are manipulatable in a mathematical way
number_rows = 5
number_columns = 7

array0s = np.zeros((number_rows,number_columns))
array1s = np.ones((number_rows,number_columns))
array5s = 5*np.ones((number_rows,number_columns))
array7s = np.full((number_rows,number_columns),7.0)

print(array0s)
print(array1s)
print(array5s)
print(array7s)


# You can set the data type in a number of ways:
array7s = np.full((number_rows,number_columns),7.0) # stores as a float
array7s = np.full((number_rows,number_columns),7) # stores as an integer

array7s = 7*np.ones((number_rows,number_columns),dtype = 'float') # stores as a float
array7s = 7*np.ones((number_rows,number_columns),dtype = 'int') # stores as an integer
array7s = 7*np.ones((number_rows,number_columns),dtype = np.float32)

# See here for more detail: https://numpy.org/doc/stable/user/basics.types.html

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]
[[1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]
[[5. 5. 5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5. 5. 5.]]
[[7. 7. 7. 7. 7. 7. 7.]
 [7. 7. 7. 7. 7. 7. 7.]
 [7. 7. 7. 7. 7. 7. 7.]
 [7. 7. 7. 7. 7. 7. 7.]
 [7. 7. 7. 7. 7. 7. 7.]]


In [5]:
# Creating a range of random numbers
random01 = np.random.random((2,3)) # 2x3 array of random numbers in the interval 0.0,1.0
randomIntRange = np.random.randint(0,10,(2,3)) #2x3 array of random numbers in the specified interval [0,10])

print(random01)
print(randomIntRange)

[[0.60805058 0.86703574 0.76631489]
 [0.567058   0.38534898 0.6823633 ]]
[[1 9 5]
 [2 4 0]]


In [6]:
# Numpy array and python list behave similarly
list = [1,2,3]
arr = np.array([1,2,3])

a=np.array([[5,6,3],[2,5,1]])
# Can check the properties of a numpy array
a.ndim # dimension
a.shape # shape
a.size #size
a.dtype #data type


dtype('int64')

In [7]:
# Generate the Numpy array:

arr = np.array([0,2,4,5,3,7,8,9,5,1])

# Take all the negative values and replace them by their negative values
arr[arr % 2 ==1] = -1*arr[arr % 2 ==1]

print(arr)


[ 0  2  4 -5 -3 -7  8 -9 -5 -1]


In [8]:
# Numpy arithmetics
#Assume:
a = np.array([[1,2,5],[7,1,3]])
b = np.array([[4,6,9],[2,5,1]])

In [9]:
# addition
add1 = a + b
add2 = np.add(a,b)

# subtraction
sub1 = a - b
sub2 = np.subtract(a,b)

# multiplication
multi1 = a * b
multi2 = np.multiply(a,b)

# Division
div1 = a / b
div2 = np.divide(a,b)

# Other useful functions:
exp1 = np.exp(a)
sqroot1 = np.sqrt(a)
sin1 = np.sin(a)
cos1 = np.cos(a)
log1 = np.log(a)

#dot product:
c = np.array([[1,2],[3,4],[5,6]])
dotp = a.dot(c)


In [10]:
# Some basic statistical functions
# Use axis=0 or axis=1 for row or column wise operations
a = np.array([[1,2,5],[7,1,3]])
# Summation
sum1 = a.sum()
sum2 = np.sum(a)

# Column wise summation
summ1row = a.sum(axis=0) # column wise
summ1row = a.sum(axis=1) # row wise

# Maximum
maxi = a.max()

# Mean (column wise)
average = np.mean(a, axis=0)

# Std
std = np.std(a)

In [11]:
a = np.array([[1,2,5],[7,1,3]])
b = np.array([[7,8,9],[10,11,12]])

# Transpose
aTr1 = np.transpose(a)
aTr2 = a.T

# Reshape:
reshape1 = np.reshape(a,(3,2)) # reshpapres to 3 rows and 2 columns
reshape2 = a.reshape(3,2)

# reshape to row:
reshapeToRow = a.reshape(6)

In [12]:
# Stack horizontally - which also seems to me like append
horizontal_stack = np.hstack([a,b])
print(horizontal_stack)

# Stack vertically - which also seems to me like adding new columns
vertical_stack = np.vstack([a,b])
print(vertical_stack)

[[ 1  2  5  7  8  9]
 [ 7  1  3 10 11 12]]
[[ 1  2  5]
 [ 7  1  3]
 [ 7  8  9]
 [10 11 12]]


In [13]:
# Concatenate arrays

# Columnwise (looks to be like horizontal stack)
ab = np.concatenate((a,b), axis=1)
print(ab)

# Rowwise (looks to be similar to the vertical stack)
ab = np.concatenate((a,b), axis=0)
print(ab)

[[ 1  2  5  7  8  9]
 [ 7  1  3 10 11 12]]
[[ 1  2  5]
 [ 7  1  3]
 [ 7  8  9]
 [10 11 12]]


In [14]:
# Save an array to a binary file (.npy)
np.save('Data/array_a',ab)

# or save several in one to an .npz file
np.savez('Data/arrays_abab',arr1=a,arr2=b)

# then you can load again
ab_reload = np.load('Data/array_a.npy')
contents = np.load('Data/arrays_abab.npz')
a_reload = contents["arr1"]
b_reload = contents["arr2"]


In [15]:
# Export array a to csv
print(a)
print(a.size)
np.around(a,1) #rounding to 1 dp
np.char.mod("%.1f",a) # storing as a string
col_header = ["a","b","c"]
row_header = ["z","y"]

np.vstack((row_header,a)) # Can use this to add a column header
np.hstack((col_header,a)) # Can use this to add row headers
np.savetxt("Data/my_a_file.csv",a,delimiter=",",fmt="%s") # %d specifies an integer and %s specifies a string

# Loading array a from csv
csv = np.loadtxt("Data/my_a_file.csv", delimiter = ',') # This doesn't work because there are strings not numbers in there

print(csv)

[[1 2 5]
 [7 1 3]]
6


ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 2 and the array at index 1 has size 3